# Videos
POST http://localhost:3000/api/videos
Content-Type: application/json

{
    "title": "video2",
    "description": "video2",
    "url": "video2"
}


###
GET http://localhost:3000/api/videos

###
GET http://localhost:3000/api/videos/63c6ad7b66af7a3aeca9b097

###
DELETE http://localhost:3000/api/videos/delete/63c6ad7b66af7a3aeca9b097

###

PUT http://localhost:3000/api/videos/update/63c6ad7b66af7a3aeca9b097
Content-Type: application/json

{
    "title": "Editei",
    "description": "video2",
    "url": "video2"
}

# Users
###
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Usuario5",
    "channel": "Usuario5",
    "email": "Usuario8",
    "password": "Usuario5"
}

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/63c6b0fd92ac32837c84fedc

###
DELETE http://localhost:3000/api/users/delete/63c6b0fd92ac32837c84fedc
###

PUT http://localhost:3000/api/users/update/63c6b0fd92ac32837c84fedc
Content-Type: application/json

{
    "name": "Mudei",
    "channel": "Mudei",
    "email": "Mudei",
    "password": "Mudei"
}

# Login
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "Usuario3",
    "password": "Usuario2"
}
