# Videos
POST http://localhost:3000/api/videos
Content-Type: application/json

{
    "title": "video2",
    "description": "video2",
    "url": "video2"
}


###
GET http://localhost:3000/api/videos

###
GET http://localhost:3000/api/videos/63c5574e4da6f17216632a35

###
DELETE http://localhost:3000/api/videos/63c5574e4da6f17216632a35

###

PUT http://localhost:3000/api/videos/63c58b7dd6a9648fd0751fe5
Content-Type: application/json

{
    "title": "Editei",
    "description": "video2",
    "url": "video2"
}

# Users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Usuario4",
    "channel": "Usuario4",
    "email": "Usuario4",
    "password": "Usuario4"
}

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/63c68d383560f3793ff33d61

###
DELETE http://localhost:3000/api/users/63c6af4f6a44e0a421cc259d
###

PUT http://localhost:3000/api/users/63c556ee4da6f17216632a33
Content-Type: application/json

{
    "name": "Mudei",
    "channel": "Mudei",
    "email": "Mudei",
    "password": "Mudei"
}

# Login
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "Usuario4",
    "password": "Usuario3"
}
